# Configuration
docs_dir: ./documentation/

# Site information
site_name: Data schema

# Theme
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

# Assets
extra_css:
  - assets/extra.css
